[versions]
agp = "8.12.0"
kotlin = "2.2.0"

annotationJvm = "1.9.1"

#kotlinx-datetime
kotlinx-datetime = "0.7.1"

# ForteanJo libraries
forteanjo-extensions = "1.0"

# Android SDK settings
android-compileSdk = "36"
android-minSdk = "27"
android-targetSdk = "36"
android-buildtools = "36.0.0"

app-versionCode = "1"
app-versionName = "1.0"

jvmTarget = "21"


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }


[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotationJvm" }
androidx-annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }

#kotlinx-datetime
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }

forteanjo-extensions = { group = "com.github.forteanjo", name = "extensions", version.ref = "forteanjo-extensions" }
