[versions]
agp = "9.3.1"
kotlin = "2.4.0"

# Dokka for documentation
dokka = "2.2.0"

# Kotlin extensions

annotationJvm = "1.10.0"

#kotlinx-datetime
kotlinx-datetime = "0.7.1"

# ForteanJo libraries
extensions_library = "1.0.2"

# Android SDK settings
android-compileSdk = "37"
android-minSdk = "27"
android-targetSdk = "37"
android-buildtools = "36.0.0"

app-versionCode = "1"
app-versionName = "1.0"

jvmTarget = "21"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotationJvm" }
androidx-annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }

#kotlinx-datetime
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }

kotlin-extensions_library = { module = "com.github.Forteanjo:Extensions_Library", version.ref = "extensions_library" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
