plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.jetbrains.dokka)

    id("maven-publish")

}

android {
    namespace = "sco.carlukesoftware.extensions"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        minSdk = libs.versions.android.minSdk.get().toInt()
    }

    compileOptions {
        sourceCompatibility = JavaVersion.toVersion(libs.versions.jvmTarget.get())
        targetCompatibility = JavaVersion.toVersion(libs.versions.jvmTarget.get())
    }

    kotlin {
        compilerOptions {
            freeCompilerArgs.addAll("-Xcontext-sensitive-resolution")
        }
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
            // Do not use withJavadocJar(), it's for the standard Javadoc task.
            // We'll create our own Javadoc JAR from Dokka's output.
        }
    }
}

dependencies {
    implementation(libs.kotlinx.datetime)
    implementation(libs.androidx.annotation)
}

// Creates a JAR file from the output of the dokkaHtml task.
// This is used to publish the documentation along with the library.
tasks.register<Jar>("javadocJar") {
    dependsOn(tasks.named("dokkaGenerateHtml"))
    archiveClassifier.set("javadoc")
    from(tasks.named("dokkaGenerateHtml").map { it.outputs.files })
}

publishing {
    publications {
        create<MavenPublication>("release") {
            groupId = "com.github.forteanjo"
            artifactId = "extensions"
            version = "1.0.4"

            afterEvaluate {
                from(components["release"])
            }

            // Include the JAR generated by the javadocJar task in the publication.
            artifact(tasks.named("javadocJar"))

            pom {
                name.set(project.name)
                description.set("Useful Kotlin extensions for Android development.")
                url.set("https://github.com/forteanjo/ExtensionsLibrary")

                licenses {
                    license {
                        name.set("The MIT License")
                        url.set("http://opensource.org/licenses/MIT")
                    }
                }

                developers {
                    developer {
                        id.set("forteanjo")
                        name.set("Your Name")
                        email.set("your.email@example.com")
                    }
                }

                scm {
                    connection.set("scm:git:git://github.com/forteanjo/ExtensionsLibrary.git")
                    developerConnection.set("scm:git:ssh://github.com/forteanjo/ExtensionsLibrary.git")
                    url.set("https://github.com/forteanjo/ExtensionsLibrary/tree/main")
                }
            }
        }
    }

    repositories {
        maven {
            name = "localRelease"
            url = uri("${layout.buildDirectory}/repo")
        }
    }
}
